services:
  app:
    container_name: main
    restart: always
    image: node:22
    ports:
      - 4005:4005
    env_file:
      - .env
    volumes:
      - ./:/usr/src/lab-ims-backend
      - /usr/src/lab-ims-backend/node_modules
      - uploads_data:/usr/src/lab-ims-backend/uploads
    working_dir: /usr/src/lab-ims-backend
    networks:
      - lab-ims-net
    command: bash -c "npm install && rm -rf dist && npm run build && npm run start:prod"

networks:
  lab-ims-net:
    external: true

volumes:
  uploads_data:
